[계산기] 허지원 미션 제출합니다!
next-step/java-calculator-unit-playground pull request #26
Opened 2024-05-11 21:13 UTC by Hheojiwon

계산기 미션 1~3단계 구현했습니다!  테스트 코드를 작성해보면서 새로 알게 된 것들이 많아서 많은 도움이 된 것 같습니다. 코드를 작성하면서 아직 헷갈리는 부분이 많은데, 피드백 주시면 참고하여 수정하겠습니다!

2024-05-12 04:18 UTC, sosow0212 requested changes
수고하셨습니다!

컨벤션 위주로 리뷰 남겼습니다. 클래스에서 필드를 언제 쓰면 좋을지, 어떤 것을 필드로 관리하면 좋을지 고민해보면 좋을 것 같습니다.

궁금한 점 있으면 단톡방에 남겨주세요!
수고하셨습니다

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/controller/CalculateController.java
> +    private final Output output;
첫줄 개행 추가해주세요

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/controller/CalculateController.java
> +
1. 불필요한 개행 있습니다
2. 정렬 습관화 해주세요!

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/controller/CalculateController.java
> +        String s=input.getString();
s보다 더 적절한 네이밍은 없을까요?

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/controller/CalculateController.java
> +
불필요한 개행 있습니다 다른 부분에서도 지워주세요~

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/domain/Calculator.java
> +    private static String customSplitString="";
1. 선언 순서는 `상수 -> 필드 ` 이렇게 해주세요!
2. 필드에 static을 붙인 이유가 있을까요?
3. 여기도 정렬이 안 되어 있습니다

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/domain/Calculator.java
> +    static int[] numArr=null;
1. 접근제어자가 없습니다
2. null 값으로 초기화하면 다른 문제는 없을까요?
3. Arr와 같이 자료형에 대한 네이밍은 피해주세요~
4. 해당 클래스에서 필드로 빼지않을 방법은 없을까요? 불필요한 값까지 관리하기보다는 정말 꼭 관리가 필요한 값이 무엇인지 고민해보면 좋을 것 같습니다

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/domain/Calculator.java
> +        strArr= s.split("[,|:]");
1. `"[,|:]"` 이건 무엇을 의미하나요? 상수처리로 뜻을 부여해주면 좋을 것 같습니다.
2. 다른 클래스도 그렇고 해당되는 모든 부분에 매개변수 혹은 필드 네이밍을 축약, 단축, 타입명을 넣지 말고 적절한 뜻을 부여해주세요!

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/domain/Calculator.java
> +        if (s.contains(SPLIT_CHAR1)&& s.contains(SPLIT_CHAR2)){
SPLIT_CHAR1~2 상수처리한 건 좋지만 적절한 네이밍이 부여되지 않았네요 ㅠ
그리고 if문 안에 조건을 메서드 분리해서 뜻을 부여해도 좋을 것 같아요

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/domain/Calculator.java
> +    public int StringCalculator(String s) {
1. `blankString(..)` 메서드 동사로 시작해주세요 검증인지 다른 것인지 구별하기 힘들어 보입니다
2.  if-else 문이 굳이 필요하지 않고 케이스를 나눠주는 메서드를 만들면 가독성 면에서도, 기능 관리 측면에서도 좋을 것 같아요
3. 메서드명이 대문자로 시작합니다 ㅠ
4. 해당 메서드로 값을 초기화하고 계산까지 하는 것 같은데 생성자를 활용해보거나 다른 방식으로 하면 좋을 것 같습니다.
해당 클래스에서 너무 많은 일을 하고 있는 것 같아서요

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/domain/Calculator.java
> +    public int[] stringToInteger(String[] s){
메서드명 동사로 시작해주세요~

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/domain/Calculator.java
> +    }
해당 메서드가 유효한가요? 지금 필드로 입력 값을 관리하는데 이렇게 하면 필드가 필요 없어 보여서요

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/domain/Calculator.java
> +        return getSum(strArr);
계산기 작동하면 무조건 덧셈한 값을 반환하는 것 같습니다

2024-05-12 04:18 UTC, sosow0212 commented on src/main/java/view/Input.java
> +    }
static, final, static final의 차이에 대해서 공부해보면 좋을 것 같습니다

2024-05-12 04:18 UTC, sosow0212 commented on src/test/java/CalculatorTest.java
> +    class calculationTest{
여기서 Nested를 사용하신 이유가 궁금합니다!

2024-05-12 04:18 UTC, sosow0212 commented on src/test/java/StringCalculatorTest.java
> +    void 음수를_입력한_경우(){
테스트명에 `예외를_발생시킨다` 이렇게 어떤 역할을 하는지 명시해주면 좋을 것 같습니다!

2024-05-12 04:18 UTC, sosow0212 commented on src/test/java/StringCalculatorTest.java
> +    void 입력이_공백인_경우_테스트(){
이것도 어떤 걸 테스트하는지 명시해주세요

2024-05-16 04:25 UTC, sosow0212 requested changes
머지할까 했는데 아쉬운 부분이 있어서 한 번만 더 RC하겠습니다!
전체적으로 정렬이 안 되어 있는데 이부분 신경써주시고, 네이밍과 메서드 순서도 신경써주세요.
객체에서 적절하게 메서드가 사용되지 않은 부분도 있는데 이부분도 고민해보시고 바꾸면 좋을 것 같습니다. 테스트도 잘하셨고 몇 가지만 고치면 좋을 것 같습니다! 👍

2024-05-16 04:25 UTC, sosow0212 commented on src/main/java/controller/CalculatorController.java
> +        this.outputView=outputView;
정렬이 안 되었네요 ㅠ

2024-05-16 04:25 UTC, sosow0212 commented on src/main/java/controller/CalculatorController.java
> +        }
이 로직은 StringCalculator의 역할 같아요
캡슐화 하시면 더 좋을 것 같습니다!

2024-05-16 04:25 UTC, sosow0212 commented on src/main/java/controller/CalculatorController.java
> +        List<String> strings;
`List<String> strings` 가 무엇을 의미하는지 모르겠습니다 적절한 네이밍으로 변경해주세요

2024-05-16 04:25 UTC, sosow0212 commented on src/main/java/controller/CalculatorController.java
> +        }
이부분도 객체 내에서 수행한 후 return을 한다면 컨트롤러가 객체의 로직을 수행하지 않을 것 같습니다!

2024-05-16 04:25 UTC, sosow0212 commented on src/main/java/domain/BasicCalculator.java
> +    public static int addNum(int num1, int num2){
static을 사용한 이유가 있을까요?
number가 여러 개 들어오면 어떻게 될까요?

2024-05-16 04:25 UTC, sosow0212 commented on src/main/java/domain/BasicCalculator.java
> +        }
👍

2024-05-16 04:25 UTC, sosow0212 commented on src/main/java/domain/StringCalculator.java
> +    private String customDelimiter="";
customDelimiter는 필드로 보이지 않습니다.
차라리 사용한다면 메서드 지역필드로 쓰는 건 어떨까요?

2024-05-16 04:25 UTC, sosow0212 commented on src/main/java/domain/StringCalculator.java
> +    }
1. 메서드 순서도 지켜주세요!  (public -> public에서 사용한 private 순서대로)
2. splitCustom 메서드에서 findCustomSplit() 메서드를 수행하면 customSplit에 대한 것이 반환될 것 같은데 그렇지 않네요 객체에게 적절한 책임과 역할을 부여해보면 좋을 것 같습니다

2024-05-16 04:25 UTC, sosow0212 commented on src/main/java/view/InputView.java
> +    public Scanner sc= new Scanner(System.in);
1. public Scanner,
public static Scanner
public final Scanner
public static final Scanner
각각 무엇이 다를까요?

2. sc라는 네이밍은 쉽게 알 수 없을 것 같습니다

2024-05-16 04:25 UTC, sosow0212 commented on src/test/java/StringCalculatorTest.java
> +}
EOF 문제 해결해주세요~

2024-05-16 20:26 UTC, Hheojiwon commented on src/main/java/controller/CalculatorController.java
> +        this.outputView=outputView;
넵 수정했습니다!

2024-05-16 20:27 UTC, Hheojiwon commented on src/main/java/controller/CalculatorController.java
> +        }
넵 객체 내에서 수행하도록 변경했습니다!

2024-05-16 21:05 UTC, Hheojiwon commented on src/main/java/view/InputView.java
> +    public Scanner sc= new Scanner(System.in);
public static: 인스턴스 생성 없이 접근 가능한 클래스 변수, 여러 인스턴스가 동일한 입력 스트림 사용할때?? 유리함
public final:  객체 생성될때 초기화 된 Scanner 객체 변경 X
public static final: 클래스 변수, 변경 불가

헷갈리는 부분 공부했습ㄴ디ㅏ.!.

2024-05-16 21:06 UTC, Hheojiwon commented on src/test/java/StringCalculatorTest.java
> +}
넵!

2024-05-16 21:07 UTC, Hheojiwon commented on src/main/java/controller/CalculatorController.java
> +        }
넵!

2024-05-16 21:07 UTC, Hheojiwon commented on src/main/java/controller/CalculatorController.java
> +        List<String> strings;
변경했습니다.!

2024-05-17 07:28 UTC, sosow0212 approved these changes
처음보다 코드가 보기 많이 좋아진 것 같아서 여기서 Approve 하겠습니다!
추가적인 객체 분리에 대한 내용은 다음 미션하면서 얘기 더 나눠봐도 좋을 것 같습니다.
수고하셨습니다 👏

2024-05-17 07:28 UTC, sosow0212 commented on README.md
>  계산기 미션 저장소
기능 구현 목록 👍

2024-05-17 07:28 UTC, sosow0212 commented on src/main/java/controller/CalculatorController.java
> +        strNumber = stringCalculator.checkSplit();
```suggestion
        List<String> strNumber = stringCalculator.checkSplit();
```

strNumber를 조금 더 이름을 풀어서 쓰면 좋을 것 같아요 자료형은 네이밍에 지양하고요!

2024-05-17 07:28 UTC, sosow0212 commented on src/main/java/domain/BasicCalculator.java
> +        this.num2=num2;
여긴 아직 정렬이 안 되었네요 ㅠ

2024-05-17 07:28 UTC, sosow0212 commented on src/main/java/domain/BasicCalculator.java
> +    private int num2;
값이 변하지 않는다면 final 키워드를 붙여도 될 것 같습니다!

2024-05-17 07:28 UTC, sosow0212 commented on src/main/java/domain/BasicCalculator.java
> +        if (num2 == 0) {
0에 상수처리해서 의미를 부여해주면 더 좋을 것 같아요 ex) CAN_NOT_DIVIDE_NUMBER

2024-05-17 07:28 UTC, sosow0212 commented on src/main/java/domain/StringCalculator.java
> +    private final String input;
```suggestion
    private static final String LAST_STRING = "\n";
    
    private final String input;
```

2024-05-20 03:45 UTC, merged